# Generated by Django 2.1.4 on 2019-01-17 03:47

import apps.servicio.models
import bienes.funciones.validaciones_upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimenciones', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('ANCHO', 'Ancho'), ('LARGO', 'Largo')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.servicio.models.foto_directorio_path, validators=[bienes.funciones.validaciones_upload.validate_image_extension])),
                ('orden', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=200)),
                ('nombre_completo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoGeografico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('tipo_inmueble', models.CharField(choices=[('TE', 'Terreno'), ('DE', 'Departamento'), ('CA', 'Casa')], max_length=2)),
                ('estado', models.CharField(choices=[('0', 'Vendido'), ('1', 'Pendiente')], default='1', max_length=1)),
                ('inscrito_registro_publico', models.BooleanField(default=True)),
                ('acabados', models.BooleanField(default=True)),
                ('fpublicacion', models.DateTimeField(auto_now_add=True)),
                ('fventa', models.DateField(blank=True, null=True)),
                ('proyeccion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, choices=[('0', 'Alto'), ('1', 'Medio'), ('2', 'Bajo')], max_length=1, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.Persona')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='servicio.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='puntogeografico',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
        migrations.AddField(
            model_name='foto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
    ]
