# Generated by Django 2.1.4 on 2019-01-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20190119_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='monto_venta',
            new_name='metros_cuadrados',
        ),
        migrations.AddField(
            model_name='servicio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='monto_dolares',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='monto_soles',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='referencia',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
    ]
