# Generated by Django 2.1.4 on 2019-01-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20190107_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntogeografico',
            old_name='modelogis',
            new_name='punto',
        ),
    ]
