# Generated by Django 2.1.4 on 2019-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_auto_20190109_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='numero',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('0', 'Vendido'), ('1', 'Pendiente')], default='1', max_length=1),
        ),
    ]
