# Generated by Django 2.1.4 on 2019-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_auto_20190110_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntogeografico',
            old_name='punto',
            new_name='latitud',
        ),
        migrations.AddField(
            model_name='puntogeografico',
            name='logitud',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
