# Generated by Django 2.1.4 on 2019-01-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_auto_20190110_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='numero',
            new_name='ordern',
        ),
    ]
