# Generated by Django 2.1.4 on 2019-01-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_auto_20190111_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo_persona',
        ),
    ]
