# Generated by Django 2.1.4 on 2019-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0011_auto_20190116_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
