# Generated by Django 2.1.4 on 2019-01-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_video_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='ordern',
            new_name='orden',
        ),
    ]
