# Generated by Django 2.1.4 on 2019-01-17 03:47

import apps.home.models
import bienes.funciones.validaciones_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.home.models.contactos_directorio_path, validators=[bienes.funciones.validaciones_upload.validate_image_extension])),
                ('titulo', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.home.models.nosotros_directorio_path, validators=[bienes.funciones.validaciones_upload.validate_image_extension])),
                ('titulo', models.CharField(max_length=1000)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.home.models.principal_directorio_path, validators=[bienes.funciones.validaciones_upload.validate_image_extension])),
                ('titulo', models.CharField(max_length=1000)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
