# Generated by Django 2.1.4 on 2019-01-07 04:37

import apps.home.models
import bienes.funciones.validaciones_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='imagen',
            field=models.ImageField(upload_to=apps.home.models.contactos_directorio_path, validators=[bienes.funciones.validaciones_upload.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen',
            field=models.ImageField(upload_to=apps.home.models.nosotros_directorio_path, validators=[bienes.funciones.validaciones_upload.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='principal',
            name='imagen',
            field=models.ImageField(upload_to=apps.home.models.principal_directorio_path, validators=[bienes.funciones.validaciones_upload.validate_image_extension]),
        ),
    ]
