# Generated by Django 2.1.4 on 2019-01-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190107_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nosotros',
            old_name='descipcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='principal',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
